// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneToOne_EF;

#nullable disable

namespace OneToOne_EF.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240529195738_seedingdata2")]
    partial class seedingdata2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneToOne_EF.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseGrade")
                        .HasColumnType("int");

                    b.Property<double>("CourseKredit")
                        .HasColumnType("float");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseGrade = 10,
                            CourseKredit = 7.5,
                            CourseName = "Game Design",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseGrade = 10,
                            CourseKredit = 7.5,
                            CourseName = "English",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseGrade = 10,
                            CourseKredit = 7.5,
                            CourseName = "Math",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseGrade = 7,
                            CourseKredit = 7.5,
                            CourseName = "Math",
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("OneToOne_EF.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LasttName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Saad",
                            LasttName = "Sabah"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ali",
                            LasttName = "Maseer"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Arai",
                            LasttName = "Sayah"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Noor",
                            LasttName = "Mohamad"
                        });
                });

            modelBuilder.Entity("OneToOne_EF.Courses", b =>
                {
                    b.HasOne("OneToOne_EF.Students", "Student")
                        .WithOne("Courses")
                        .HasForeignKey("OneToOne_EF.Courses", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OneToOne_EF.Students", b =>
                {
                    b.Navigation("Courses")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
